### ISSUE TITLE
What is the purpose of this standard?

### ISSUE THREAD

**Issue by LJWatson** [alphagov/accessibility-guidance#11]
We need to decide what it is we want to create. Expectations are changing based on issues (especially #3, #4, #5, #6 and #7).

Is this a high-level intro or a thorough explanation, and of what (accessibility at Gov.UK, WCAG, both, neither)?

Where do we draw the line between reinventing the wheel and pointing people to existing descriptions, definitions and other supporting materials?

Are we trying to define a new government standard, change the existing one, or just help understand the current status quo?

Are we trying to explain how to solve problems (common ones or otherwise), or provide some insight into general areas for consideration?

**Comment by aduggin** [comment]
This is all stuff we are trying to figure :)

Off the back of the discovery research that we have been doing and the session at the away day where we reviewed the current guidance in the service manual a few things have become clear:

* People responsible for delivery services want to and need to know what is required of them with regard to accessibility.
* The current guidance is a mixture of setting a standard (what you have to do, for example meet WCAG 2.0 AA) and suggestions on how to achieve it and is confusing about what is required.
* Most people are unfamiliar with WCAG and linking off to a long technical document does not help people figure out what they need to do.

I think we need a document that clearly explains what standard of accessibility products and services need to reach but also provides some extra information that that helps people understand what WCAG is and what it includes.  

I want us to come up with at least one draft version that we can put it in front of some people that are working on delivery teams to find out if what we have come up with is helpful and then iterate it. I want us to do user research around this rather than us just writing and publishing something and assuming what we have done is helpful.

What you have come up with so far is brilliant. It is already helping us see that we need to figure out a few things:

* What are we going to say is required? Just meeting WCAG 2 AA, or some AAA where possible?  Is being compatible with assistive technologies required?  Is doing usability testing with people with impairments required? Is meeting the GOV.UK content guidance (reading level) required?
* What extra information is helpful? What WCAG is, what it is for and what it covers?
* How much details should we go into?
* Do we link off to further resources - and are these our own or existing resources?

I'm thinking that we could come up with 3 versions to do some user testing with (and also to help us explore what good may look like)

1. A version that only contains only what is required - with no extra context or information about WCAG
2. A version that contains what is required plus some succinct extra information about WCAG and what Perceivable, Operable, Understandable and Robust includes (similar to your first draft)
3. A version that contains what is required plus the extra contextual information about WCAG and more detailed information about what Perceivable, Operable, Understandable and Robust includes.

**Comment by accessiblewebuk** [comment]
Sounds good, but I think there are real difficulties with doing user testing of this. Proper user testing would involve teams using this either over the course of a real project, or some kind of dummy project - neither of which are very practical in getting things iterated quickly. We can get teams to review the documentation but that isn't the same. I would say the same challenge applies to the service manual generally so we could try and learn from their experience of iterating the content and structure?

**Comment by chrismoorembe** [comment]
I think we should start with writing a very simple overview explaining what users must be able to do so a service can be classed as accessible. To learn more, we then link to Leonie's document which goes into a bit more detail about WCAG and  covers the checkpoints that need to be met. Like the GOV.UK elements page,  we may need to give examples of how this can be achieved if they are not already covered within the service manual. To ensure the standard of writing is high and is not changed without our knowledge, I think it would be beneficial if we could write our own instead of pointing to external resources.

**Comment by LJWatson** [comment]
Based on conversation with @aduggin yesterday...

The standard doc is now a (very) minimal description of the standard as it is currently.

The old standards.md doc is now called wcag.md and it's been tweaked slightly to reference the actual standards.md doc.

This <a href="https://github.com/alphagov/accessibility-guidance/commit/4828a3ee5e5ffdd1658d806e700625ba1d0a0466">commit</a> is the one with these updates.

**Comment by aduggin** [comment]
@accessiblewebuk with regard to user research being difficult - it will be easy to get some people to read it and see if there are any bits they don't understand or require more information about - or any other issues they have with it.  We did this lots of the [Pension Wise](https://www.pensionwise.gov.uk/) project. It's amazing how much you learn and how even small changes in content can improve people understanding
