### ISSUE TITLE
Standard: things to do to be percievable

### ISSUE THREAD

**Issue by aduggin** [alphagov/accessibility-guidance#4]
People need to do more than 'Provide text alternatives for images' - they need to provide text alternatives that communicates the same information that is being being communicated visually by an image.

All interface controls need appropriate text - such as form controls and multimedia player buttons

All frames/iframes need appropriate titles

People also need to ensure that all information is still communicated visually when page colours are changed (for example by changing the browser settings or when using screen magnification software such as ZoomText)

**Comment by aduggin** [comment]
Should we expand on 'Use the proper mark-up for every feature' and call out the importance of making using the correct markup for forms and tabular data (would be good to link to guidance on how to do this) - as these are the most common errors identified in accessibility reviews.

**Comment by aduggin** [comment]
Color is not used as the sole method of conveying content or distinguishing visual elements

**Comment by LJWatson** [comment]
"All interface controls need appropriate text - such as form controls and multimedia player buttons"

This is not alternative text. It's accessible name, covered under Robust (4.1.2).

"All frames/iframes need appropriate titles"

This is already included under Operable.

"Should we expand on 'Use the proper mark-up for every feature' and call out the importance of making using the correct markup for forms and tabular data
(would be good to link to guidance on how to do this) - as these are the most common errors identified in accessibility reviews."

Think this could be useful, but again returning to the question of what we're trying to do here. Is this an intro, or do we want to start explaining things and pointing to techniques and solutions?

**Comment by accessiblewebuk** [comment]
If we enforce "Do not use images of text" we risk excluding useful images like diagrams or images which are alternatives for text. While I agree with the reasoning behind avoiding images of text, I think it is too restrictive. To give an example if we had a graph with text overlaid over the image that would pass, but if we had a graph with embedded text that would fail, even if there was a fully accessible alternative version of the information like a data table.

**Comment by accessiblewebuk** [comment]
Add in: provide audio description of video where needed

**Comment by chrismoorembe** [comment]
Including text within images could be problematic for users who use the web browser to increase text size, text within an image will be smaller on mobile devices, text within an  image is not exposed to a search engines, text within an image can become pixelated or blurred when magnified, some users find it easier to perceive data from an image rather than use a table.

**Comment by accessiblewebuk** [comment]
I understand and agree with all the arguments against text within images, however there are exceptions e.g. 

- Text within an SVG image shouldn't become blurred or pixelated when magnified (that may be a big assumption on my part, and I recognise that SVG images aren't common compared to JPG and GIF)
- Alt text for an image is exposed to search engines

If we do decide that not allowing text within images is going to be enforced then it has implications for any diagrams that are published - strictly enforcing the guideline means that even if a full separate explanation is provided on the same page, we have to fail it. I don't believe that is a workable process. It also means no publishing of maps or banners with informative text in them, the only things allowed would be logos.

**Comment by chrismoorembe** [comment]
Agreed, so the advice should be to avoid using text on images where possible, as users  on smaller mobile devices and users who have low vision have less control over reading text on images. We could lists the types of images where text should not be included, and lists the types of situations where it is acceptable and how they should be supported. Content designers try to avoid using diagrams where possible and aim to clearly explain instructions within the text, as diagrams just don't render very well on smaller devices. Perhaps a PDF would be more suitable for diagrams if they are not in SVG format, as they do offer slightly more scalability rather than JPEG or GIF.
